env: dev

spark:
  app_name: "RAW2DIS"
  master: "local[*]"
  log_level: "ERROR"
  config:
    spark.sql.shuffle.partitions: 2
    spark.driver.memory: "2g"
    spark.sql.session.timezone: "UTC"

raw_layer:
  path: "data/raw/"
  format: "csv"
  options:
    csv:
      header: true
      inferSchema: false
    parquet:
      mergeSchama: true

dis_layer:
  path: "data/distilled/"
  format: "hudi"
  mode: "upsert"
  hudi:
    table_type: "COPY_ON_WRITE"
    preconbine_field: "updated_timestamp"